# Generated by Django 3.2.8 on 2021-10-16 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='customer',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='customer',
            new_name='product',
        ),
    ]
